### ISSUE TITLE
Employer / My Jobs / Click View applicants

### ISSUE THREAD

**Issue by Jamalatm** [Anupriyabanger/Bee-Recruiter#1233]
The statuses like "New Applications", "Applied", "Shortlisted", etc..  add a count next to each tab to show how many applicants are in each category.

**Search:**
"Search Applicant" is clear. Maybe zoom the icon of a magnifying glass inside the search bar for a better user experience.
Add by fillters

The "Select" column might have checkboxes; it would be good if there's an option to select all at the top.
Each column title has an arrow, presumably for sorting. Ensure it's clickable with clear ascending/descending indicators.
Consider providing filters for columns like "Skills" or "Current Designation" to help Employers (Users) filter applicants easily.
If there is  no applicants, a message like "No applicants found" would be helpful.

Icons (languages,Thems....) are a bit ambiguous without tooltips.  provide labels or tooltips on hover, (Languages flags)

<img width="960" alt="2023-10-22 (3)" src="https://github.com/Anupriyabanger/Bee-Recruiter/assets/133124176/56ca9bd7-b18c-48f0-8896-eae5c8def7aa">

Afetr click view applicant

**Comment by SaurabhattJi** [comment]
@Jamalatm 

- We have included checkboxes in this interface, but there is no data available for this specific job, which is why you are seeing a no data page. However, the arrows are still functional. 
- They can be clicked to sort the available data in either ascending or descending order. To enhance the user experience, we have also implemented tooltips for additional information and guidance.

**Comment by Jamalatm** [comment]
@SaurabhattJi  what about other comments !

**Comment by SaurabhattJi** [comment]
@Jamalatm So sorry i forgot to attach the picture
![image](https://github.com/Anupriyabanger/Bee-Recruiter/assets/120307815/46d0aa6e-fd8d-4e8b-afea-e1d76797ff56)
Here
